name: Java Maven Build & Test

on:
  push:
    branches:
      - develop  # Set your main branch name here
  pull_request:
    branches:
      - develop  # Set your main branch name here


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER_PACKAGE_READ: ${{ secrets.USER_PACKAGE_READ }}
      TOKEN_PACKAGE_READ: ${{ secrets.M2_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          repo-token: ${{ secrets.M2_PASSWORD }}
      - name: Build with Maven
        run: mvn clean install -DskipTests
