name: Java Maven Build & Test

on:
  push:
    branches:
      - develop  # Set your main branch name here
  pull_request:
    branches:
      - develop  # Set your main branch name here


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Github authentication
        env:
          token: ${{ secrets.M2_PASSWORD }}
        run: printenv
 #     - name: Build with Maven
  #      run: mvn clean install -DskipTests
